// @ts-nocheck
// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "news_categories_query.proto" (package "NewsCategory", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { NewsCategoryQuery } from "./news_categories_query";
import type { AdminGetAllNewsCategoriesRequest } from "./news_categories_query";
import type { GetDetailNewsCategoryRequest } from "./news_categories_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../../../../core/apis/utils/result";
import type { GetAllNewsCategoriesRequest } from "./news_categories_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service NewsCategory.NewsCategoryQuery
 */
export interface INewsCategoryQueryClient {
    /**
     * @generated from protobuf rpc: GetAllNewsCategories
     */
    getAllNewsCategories(input: GetAllNewsCategoriesRequest, options?: RpcOptions): UnaryCall<GetAllNewsCategoriesRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetDetailNewsCategory
     */
    getDetailNewsCategory(input: GetDetailNewsCategoryRequest, options?: RpcOptions): UnaryCall<GetDetailNewsCategoryRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetAllNewsCategories
     */
    adminGetAllNewsCategories(input: AdminGetAllNewsCategoriesRequest, options?: RpcOptions): UnaryCall<AdminGetAllNewsCategoriesRequest, CommonResult>;
}
/**
 * @generated from protobuf service NewsCategory.NewsCategoryQuery
 */
export class NewsCategoryQueryClient implements INewsCategoryQueryClient, ServiceInfo {
    typeName = NewsCategoryQuery.typeName;
    methods = NewsCategoryQuery.methods;
    options = NewsCategoryQuery.options;
    _transport: RpcTransport;
    constructor(_transport: RpcTransport) {
        this._transport = _transport;
    }
    /**
     * @generated from protobuf rpc: GetAllNewsCategories
     */
    getAllNewsCategories(input: GetAllNewsCategoriesRequest, options?: RpcOptions): UnaryCall<GetAllNewsCategoriesRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllNewsCategoriesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDetailNewsCategory
     */
    getDetailNewsCategory(input: GetDetailNewsCategoryRequest, options?: RpcOptions): UnaryCall<GetDetailNewsCategoryRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailNewsCategoryRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetAllNewsCategories
     */
    adminGetAllNewsCategories(input: AdminGetAllNewsCategoriesRequest, options?: RpcOptions): UnaryCall<AdminGetAllNewsCategoriesRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminGetAllNewsCategoriesRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
