// @ts-nocheck
// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "news_posts_query.proto" (package "NewsPosts", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { NewsPostsQuery } from "./news_posts_query";
import type { AdminGetAllNewsPostsRequest } from "./news_posts_query";
import type { GetDetailNewsPostsRequest } from "./news_posts_query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResult } from "../../../../../core/apis/utils/result";
import type { GetAllNewsPostsRequest } from "./news_posts_query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service NewsPosts.NewsPostsQuery
 */
export interface INewsPostsQueryClient {
    /**
     * @generated from protobuf rpc: GetAllNewsPosts
     */
    getAllNewsPosts(input: GetAllNewsPostsRequest, options?: RpcOptions): UnaryCall<GetAllNewsPostsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: GetDetailNewsPosts
     */
    getDetailNewsPosts(input: GetDetailNewsPostsRequest, options?: RpcOptions): UnaryCall<GetDetailNewsPostsRequest, CommonResult>;
    /**
     * @generated from protobuf rpc: AdminGetAllNewsPosts
     */
    adminGetAllNewsPosts(input: AdminGetAllNewsPostsRequest, options?: RpcOptions): UnaryCall<AdminGetAllNewsPostsRequest, CommonResult>;
}
/**
 * @generated from protobuf service NewsPosts.NewsPostsQuery
 */
export class NewsPostsQueryClient implements INewsPostsQueryClient, ServiceInfo {
    typeName = NewsPostsQuery.typeName;
    methods = NewsPostsQuery.methods;
    options = NewsPostsQuery.options;
    _transport: RpcTransport;
    constructor(_transport: RpcTransport) {
        this._transport = _transport;
    }
    /**
     * @generated from protobuf rpc: GetAllNewsPosts
     */
    getAllNewsPosts(input: GetAllNewsPostsRequest, options?: RpcOptions): UnaryCall<GetAllNewsPostsRequest, CommonResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllNewsPostsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDetailNewsPosts
     */
    getDetailNewsPosts(input: GetDetailNewsPostsRequest, options?: RpcOptions): UnaryCall<GetDetailNewsPostsRequest, CommonResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDetailNewsPostsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetAllNewsPosts
     */
    adminGetAllNewsPosts(input: AdminGetAllNewsPostsRequest, options?: RpcOptions): UnaryCall<AdminGetAllNewsPostsRequest, CommonResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminGetAllNewsPostsRequest, CommonResult>("unary", this._transport, method, opt, input);
    }
}
